"""Deterministic attachment of validated legal Rule records."""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from adapters.common.contracts import SearchCitation

PACKAGE_ROOT = Path(__file__).resolve().parent
RULE_CATALOG_PATH = PACKAGE_ROOT / "rule_catalog.json"
ACTIVE_REVIEW_STATUSES = {"HIGH", "REVIEW", "LOW"}
PRODUCT_ROUTE_BY_STORE = {
    "FS11_FOOD_REVIEW": "FOOD_REVIEW",
    "FS21_HFF_REVIEW": "HFF_REVIEW",
}


class RuleCatalogError(RuntimeError):
    """The local Rule catalog is absent or internally inconsistent."""


@lru_cache(maxsize=1)
def load_rule_catalog() -> dict[str, Any]:
    """Load and validate the versioned catalog once per process."""

    try:
        catalog = json.loads(RULE_CATALOG_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise RuleCatalogError("RULE_CATALOG_UNAVAILABLE") from error

    if not catalog.get("catalog_version"):
        raise RuleCatalogError("RULE_CATALOG_VERSION_MISSING")
    aliases = catalog.get("violation_type_aliases")
    rules = catalog.get("rules")
    if not isinstance(aliases, dict) or not isinstance(rules, list):
        raise RuleCatalogError("RULE_CATALOG_INVALID")

    seen: set[str] = set()
    for rule in rules:
        if not isinstance(rule, dict):
            raise RuleCatalogError("RULE_CATALOG_INVALID")
        rule_id = str(rule.get("unified_rule_id") or "")
        if (
            not rule_id
            or rule_id in seen
            or rule.get("status") != "ACTIVE"
            or not rule.get("violation_type")
            or not rule.get("source_document")
            or not rule.get("article")
            or not rule.get("source_url")
        ):
            raise RuleCatalogError("RULE_CATALOG_INVALID")
        seen.add(rule_id)
    return catalog


def _candidate_review(review: dict[str, Any]) -> bool:
    score = review.get("risk_score")
    return (
        review.get("status") in ACTIVE_REVIEW_STATUSES
        or (type(score) is int and score > 0)
    )


def _citation(record_id: str, rule: dict[str, Any]) -> SearchCitation:
    excerpt = " | ".join(
        str(value)
        for value in (
            rule.get("source_document"),
            rule.get("article"),
            rule.get("condition_text"),
            rule.get("decision_text"),
        )
        if value
    )
    return SearchCitation(
        record_id=record_id,
        file_name="rule_catalog.json",
        source=str(rule.get("source_url") or "") or None,
        page=None,
        excerpt=excerpt,
    )


def attach_local_rules(
    *,
    data: dict[str, Any],
    store_alias: str,
) -> tuple[list[str], list[SearchCitation]]:
    """Replace model Rule IDs with catalog IDs for each candidate review.

    File Search remains responsible for official evidence and cases. Rule IDs
    are derived only from the validated local catalog, so no vector-store
    search call or semantic top-k selection is involved.
    """

    product_route = PRODUCT_ROUTE_BY_STORE.get(store_alias)
    if not product_route:
        raise RuleCatalogError("RULE_CATALOG_ROUTE_UNSUPPORTED")

    catalog = load_rule_catalog()
    aliases = catalog["violation_type_aliases"]
    rules_by_type: dict[str, list[dict[str, Any]]] = {}
    for rule in catalog["rules"]:
        if rule.get("route_scope") not in {"BOTH", product_route}:
            continue
        rules_by_type.setdefault(str(rule["violation_type"]), []).append(rule)

    attached_ids: list[str] = []
    citations: list[SearchCitation] = []
    unresolved = False
    for review in data.get("violation_reviews", []):
        if not isinstance(review, dict):
            continue
        # Never trust or retain Rule IDs generated by the model.
        review["rule_ids"] = []
        uncertainty = review.setdefault("uncertainty_codes", [])
        if not _candidate_review(review):
            review["uncertainty_codes"] = [
                code for code in uncertainty if code != "SEARCH_NO_RULE"
            ]
            continue

        mapped_types = aliases.get(str(review.get("violation_type") or ""), [])
        matched_rules = [
            rule
            for mapped_type in mapped_types
            for rule in rules_by_type.get(mapped_type, [])
        ]
        if not matched_rules:
            if "SEARCH_NO_RULE" not in uncertainty:
                uncertainty.append("SEARCH_NO_RULE")
            unresolved = True
            continue

        review_ids = [
            f"RULE::{product_route}::{rule['unified_rule_id']}"
            for rule in matched_rules
        ]
        review["rule_ids"] = review_ids
        review["uncertainty_codes"] = [
            code for code in uncertainty if code != "SEARCH_NO_RULE"
        ]
        attached_ids.extend(review_ids)
        citations.extend(
            _citation(record_id, rule)
            for record_id, rule in zip(review_ids, matched_rules)
        )

    output_uncertainty = data.setdefault("uncertainty_codes", [])
    if unresolved:
        if "SEARCH_NO_RULE" not in output_uncertainty:
            output_uncertainty.append("SEARCH_NO_RULE")
    else:
        data["uncertainty_codes"] = [
            code
            for code in output_uncertainty
            if code != "SEARCH_NO_RULE"
        ]

    unique_ids = list(dict.fromkeys(attached_ids))
    unique_citations = list(
        {
            (item.record_id, item.file_name): item
            for item in citations
        }.values()
    )
    return unique_ids, unique_citations
